# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-17 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notice',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_told',
            field=models.CharField(default='', max_length=300, verbose_name='老师有话说'),
        ),
    ]
